### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by york8817612** [SYJourney/journey_client#1]
nxfile.h': No such file or directory

**Comment by SYJourney** [comment]
the nolifenx library is required, it's the link at the bottom of the description

**Comment by york8817612** [comment]
Sorry I can not find where nxfile.h in nolifenx

**Comment by SYJourney** [comment]
Oh I think the nxfile.h was from an old version. It should be file.h in the nolifenx from the link, so just change the name.
